name: Build hydra-data docker image

on:
  push:
    branches:
      - KPMP-5100_build-image-with-gradle

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'oracle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5
    - name: Run build with Gradle Wrapper
      run: |
        ./gradlew build docker
        docker push kingstonduo/hydra-data:gradlew-build